[build]
  command = "npm run build" # Change this based on your build command
  publish = "dist" # Change this to your frontend build folder (e.g., "build" or "out")

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app"
  status = 200

[[redirects]]
  from = "/r/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
